import type { Metadata } from "next";
import { Roboto, Lora } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  variable: "--font-roboto",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${lora.variable} min-h-screen bg-gray-900 font-lora flex flex-col`}
      >
        <div className="flex-1">
          {children}
        </div>

        {/* Footer */}
        <footer className="relative z-10 bg-[#343A40] w-full">
          <div className="px-[78px] py-6">
            <p className="text-sm text-gray-100">
              2025 | Q2 Interactive s.r.o.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
